const Images = {
  dashboard_first_image: require('../assets/dashboard_first_image.png'),
  white_fill: require('../assets/white_fill.png'),
  banner1: require('../assets/banner1.png'),
  banner2: require('../assets/banner2.png'),
  banner3: require('../assets/banner3.png'),
  redirect_button: require('../assets/redirect_button.png'),
  whiteOverlay: require('../assets/whiteOverlay.png'),
  banner_detail_image_overlay: require('../assets/banner_detail_image_overlay.png'),
  back_button_icon: require('../assets/back_button_icon.png'),
  emergency: require('../assets/emergency.png'),
  konut: require('../assets/konut.png'),
  down_arrow: require('../assets/down_arrow.png'),
  redirection_top_banner: require('../assets/redirection_top_banner.png'),
  vakif_redirect: require('../assets/vakif_redirect.png'),
  halk_redirect: require('../assets/halk_redirect.png'),
  ziraat_redirect: require('../assets/ziraat_redirect.png'),
  home_active: require('../assets/tab_icons/home_active.png'),
  home_passive: require('../assets/tab_icons/home_passive.png'),
  map_active: require('../assets/tab_icons/map_active.png'),
  map_passive: require('../assets/tab_icons/map_passive.png'),
  phone_active: require('../assets/tab_icons/phone_active.png'),
  phone_passive: require('../assets/tab_icons/phone_passive.png'),
  gray_up_arrow: require('../assets/gray_up_arrow.png'),
  map: require('../assets/map.png'),
  call: require('../assets/call.png'),
  route: require('../assets/route.png'),
  contact_top_banner: require('../assets/contact_top_banner.png'),
  right_button: require('../assets/right.png'),
  contact_topbar: require('../assets/contact_topbar.png'),
  marker: require('../assets/marker.png'),
  white_route: require('../assets/white_route.png'),
  menu: require('../assets/menu.png'),
  down_arrow_grey: require('../assets/down_arrow_grey.png'),
  call_white: require('../assets/call_white.png'),
  route_white: require('../assets/route_white.png'),
  back_button_grey_icon: require('../assets/back_button_grey_icon.png'),
};

export { Images };
